### ISSUE TITLE
Are you going to release/publish the current version as a new version?

### ISSUE THREAD

**Issue by pierre-borckmans** [sbt/sbt-dirty-money#10]
Hi @eed3si9n!
Thanks for this nice plugin.

I was wondering if you were planning to release it soon with the AutoPlugin format changes that you recently made?

At the moment we are publishing and hosting our own version of this plugin.
Thanks for letting me know!

**Comment by xuwei-k** [comment]
I will release new version if there is no objections /cc @eed3si9n

**Comment by eed3si9n** [comment]
Done https://github.com/sbt/sbt-dirty-money/releases/tag/v0.2.0
